USE db;
CREATE DATABASE IF NOT EXISTS DB;

CREATE TABLE IF NOT EXISTS Region (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  location_id INT DEFAULT NULL,
  FOREIGN KEY (location_id) REFERENCES Region(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Store (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  region_id INT NOT NULL,
  FOREIGN KEY (region_id) REFERENCES Region(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS User (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  location_id INT NOT NULL,
  FOREIGN KEY (location_id) REFERENCES Region(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS User_Stores (
  user_id INT NOT NULL,
  store_id INT NOT NULL,
  PRIMARY KEY (user_id, store_id),
  FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (store_id) REFERENCES Store(id) ON DELETE CASCADE
);
